### PR TITLE
Initialize pointer-sized arguments to bitvectors

### LINKED ISSUE #279: False positive with must-fail heuristic on Macaw pointer dereferences
GREASE gives a pretty poor result on the following very simple Macaw S-expression program that dereferences `rdi + 4`. This is ultimately due to our lack of fine-grained tracking of errors arising from the Macaw memory model (https://github.com/GaloisInc/macaw/issues/429).
```
(defun @test ((regs X86Regs)) X86Regs
  (start start:
    (let ptr0 (get-reg rdi regs))
    (let offset (bv 64 4))
    (let ptr1 (pointer-add ptr0 offset))
    (let _ (pointer-read (Bitvector 8) le ptr1))
    (return regs)))
```
```
cabal run exe:grease -- --symbol test bad.x64.cbl

Analyzing from entrypoint 'test' 
Finished analyzing 'test'. Likely bug: unavoidable error (safety condition is unsatisfiable) at internal
internal: error: in test
PointerRead outside of static memory range (known BlockID 0): bvSum crdi_offset@69:bv 0x4:[64]

Concretized arguments:

rcx: 0000000000000000
rdx: 0000000000000000
rsi: 0000000000000000
rdi: 0000000000000000
r8: 0000000000000000
r9: 0000000000000000
r10: 0000000000000000
```

(commit: 0f0c1541f2b8d6f84355382b6baec0e140e095ba)

### LINKED ISSUE #283: Print pointers with empty memshapes differently
Right now we will print a pointer to an empty memshape as:
```
rdi: 000008+0000000000000000

000008: 
```

But then there actually isnt an object allocated for 0008 because the ArgShape actually initializes rdi to a llvm bv pointer. I think this is a bit confusing for users (and me since I got fooled by it for a second 😆 )

since rdi is treated effectively as a symbolic bv ptr maybe it would be better to print it how those are printed?

This behavior can be observed with the program from https://github.com/GaloisInc/grease/issues/279, where an error will occur in the 0x0 allocation despite rdi being initialized as:

```
rdi: 000008+0000000000000000

000008: 
```

### PR DESCRIPTION
**Pull request by langston-barrett**
Previously, we initialized these as pointers (`ShapePtr`) to empty allocations (i.e., empty `PtrTarget`s). However, the code in `Setup` went on to treat such pointers to empty allocations as plain bitvectors (i.e., `LLVMPointer`s with block number 0), which led to some confusing output seen in issue #283.

This sidesteps the confusion by never creating such zero-size pointers in the first place. Instead, initialize pointer-size registers to be symbolic bitvectors (`ShapePtrBV`) from the start. If they are treated as pointers during execution, then make them pointers to (at first) one uninitialized byte.

This doesn't yet fix #279, which will still require #284.

Needs:

- [x] Fix tests
- [x] Adjust note about empty pointer targets

Fixes #283, or at least ameliorates the problem.

### CODE REVIEW

File: grease/src/Grease/Heuristic.hs [hunk 1]
```diff
@@ -121,6 +122,12 @@ refinePtrArg ::
   IO (HeuristicResult ext argTys)
 refinePtrArg la args modify sel =
   case args ^. selectArg sel of
+    ShapeExt (ShapePtrBV _tag w) | Just Refl <- testEquality w ?ptrWidth -> do
+      let pt = ptrTarget Nothing Seq.empty
+      doLog la $ Diag.HeuristicPtrTarget pt
+      pt' <- modify pt
+      let args' = args & selectArg sel .~ ShapeExt (ShapePtr NoTag (Offset 0) pt')
```
Comment (2over12) [inline grease/src/Grease/Heuristic.hs:129]: Im trying to work out if this matches up with the "heuristics wont make empty memshapes" piece. Im assuming that the modify provided is always supposed to grow this target allocation, is that always true?

**Review by 2over12 — APPROVED** [review]

File: grease/src/Grease/Heuristic.hs (hunk 1 above)
Comment (langston-barrett) [reply grease/src/Grease/Heuristic.hs:129]: Yeah, in practice this is always one of the `.*(g|G)rowPtrTarget.*` functions.
