### PR TITLE
DWARF: Add debug logging for dwarf

### LINKED ISSUE #470: Print errors in constructing dwarf shapes
We should make `fromDwarfInfo` collect a log of parsing errors, and individual shapes return an Either so we know why a shape failed to parse

### PR DESCRIPTION
**Pull request by 2over12**
Adds debug output, decided to pass a logging action down up to individual shape parsing. Closes #470

### CODE REVIEW

File: grease-exe/tests/sanity/pass/dwarf-fail-to-parse-log/test.c [hunk 1]
```diff
@@ -0,0 +1,19 @@
+/* Copyright (c) Galois, Inc. 2025 */
+
+// Tests that we log a failure to parse for an unsupported dwarf type
```
Comment (langston-barrett) [inline grease-exe/tests/sanity/pass/dwarf-fail-to-parse-log/test.c]: Which type is unsupported?

File: grease/src/Grease/Macaw/Dwarf/Diagnostic.hs [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+import Grease.Diagnostic.Severity (Severity (..))
+import Prettyprinter qualified as PP
+
+data Diagnostic where
+  FailedToParse :: Dwarf.Subprogram -> String -> Diagnostic
+  deriving (Show)
+
+instance PP.Pretty Diagnostic where
+  pretty = \case
+    FailedToParse subprog msg -> PP.vcat [PP.pretty "Failed to parse dwarf shape in:", PP.viaShow subprog, PP.pretty "DWARF message: ", PP.pretty msg]
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf/Diagnostic.hs]:
```suggestion
    FailedToParse subprog msg -> PP.vcat [PP.pretty "Failed to parse DWARF shape in:", PP.viaShow subprog, PP.pretty "DWARF message: ", PP.pretty msg]
```
also, long line...

File: grease/src/Grease/Macaw/Dwarf.hs [hunk 3]
```diff
@@ -97,70 +107,66 @@ loadDwarfPreconditions ::
...
  where
-  extractTypeInternal :: MDwarf.TypeRef -> Maybe MDwarf.TypeApp
+  extractTypeInternal :: MDwarf.TypeRef -> Either String MDwarf.TypeApp
   extractTypeInternal vrTy =
-    do
-      let mp = MDwarf.subTypeMap sprog
-      (mbtypeApp, _) <- Map.lookup vrTy mp
-      rightToMaybe mbtypeApp
+    let mp = MDwarf.subTypeMap sprog
+     in Maybe.maybe (Left $ "No type for typeref: " ++ show vrTy) (\(a, _) -> a) (Map.lookup vrTy mp)
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf.hs]: IMO would be more readable as a `case` but nbd

File: grease/src/Grease/Macaw/Dwarf.hs [hunk 4]
```diff
@@ -97,70 +107,66 @@ loadDwarfPreconditions ::
...
   padding :: Integral a => a -> MemShape w NoTag
   padding w = Uninitialized (toBytes w)
   -- if we dont know where to place members we have to fail/just place some bytes
-  buildMember :: CLM.HasPtrWidth w => Word64 -> MDwarf.Member -> Maybe (Word64, Seq.Seq (MemShape w NoTag))
+  buildMember :: CLM.HasPtrWidth w => Word64 -> MDwarf.Member -> Either String (Word64, Seq.Seq (MemShape w NoTag))
   buildMember loc member =
     do
-      memLoc <- MDwarf.memberLoc member
-      padd <- Just (if memLoc == loc then Seq.empty else Seq.singleton (padding $ memLoc - loc))
+      memLoc <- Maybe.maybe (Left $ "Expected location for member: " ++ show member) Right $ MDwarf.memberLoc member
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf.hs]: Same re: `case`

File: grease/src/Grease/Macaw/Dwarf.hs [hunk 5]
```diff
@@ -190,7 +196,7 @@ nullPtr =
   let zbyt = TaggedByte{taggedByteTag = NoTag, taggedByteValue = 0}
    in Exactly (take (fromInteger $ CT.intValue ?ptrWidth `div` 8) $ repeat $ zbyt)
 
-constructPtrMemShapeFromRef :: CLM.HasPtrWidth w => TypeUnrollingBound -> Subprogram -> VisitCount -> MDwarf.TypeRef -> Maybe (MemShape w NoTag)
+constructPtrMemShapeFromRef :: CLM.HasPtrWidth w => TypeUnrollingBound -> Subprogram -> VisitCount -> MDwarf.TypeRef -> Either String (MemShape w NoTag)
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf.hs]: Long line

File: grease/src/Grease/Macaw/Dwarf.hs [hunk 6]
```diff
@@ -190,7 +196,7 @@ nullPtr =
...
 constructPtrMemShapeFromRef bound@(TypeUnrollingBound tyUnrollBound) sprog vcount ref =
   let ct = fromMaybe 0 (Map.lookup ref vcount)
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf.hs]: This keeps the argument list a little more concise:
```suggestion
constructPtrMemShapeFromRef bound sprog vcount ref =
let TypeUnrollingBound tyUnrollBound = bound
    ct = fromMaybe 0 (Map.lookup ref vcount)
```

File: grease/src/Grease/Macaw/Dwarf/Diagnostic.hs [hunk 7]
```diff
@@ -0,0 +1,19 @@
+{-# LANGUAGE LambdaCase #-}
+
+module Grease.Macaw.Dwarf.Diagnostic (Diagnostic (..), severity) where
+
+import Data.Macaw.Dwarf qualified as Dwarf
+import Grease.Diagnostic.Severity (Severity (..))
+import Prettyprinter qualified as PP
+
+data Diagnostic where
+  FailedToParse :: Dwarf.Subprogram -> String -> Diagnostic
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf/Diagnostic.hs:10]: This `String` seems like it could be an ADT with its own `Pretty` instance. That would separate the issue of presentation from error handling (leading to more concise parsing code), and would be more future-proof in case we want to programatically handle these errors at some point.

File: grease/src/Grease/Macaw/Dwarf.hs [hunk 8]
```diff
@@ -218,23 +229,23 @@ pointerShapeOfDwarf ::
...
 pointerShapeOfDwarf _ _ r _ (MDwarf.UnsignedIntType _) = intPtrShape r
 pointerShapeOfDwarf _ tyUnrollBound _ sprog (MDwarf.PointerType _ tyRef) =
-  let memShape = constructPtrTarget tyUnrollBound sprog Map.empty =<< extractType sprog =<< tyRef
+  let memShape = constructPtrTarget tyUnrollBound sprog Map.empty =<< extractType sprog =<< Maybe.maybe (Left $ "Pointer missing pointee") Right tyRef
       pointerShape = ShapePtr NoTag (Offset 0) <$> memShape
    in (C.Some <$> pointerShape)
-pointerShapeOfDwarf _ _ _ _ _ = Nothing
+pointerShapeOfDwarf _ _ _ _ ty = Left $ "Unsupported base dwarf type: " ++ show ty
 
 -- Stops after the first nothing to avoid adding shapes after
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf.hs]:
```suggestion
-- Stops after the first 'Left' to avoid adding shapes after
```

File: grease/src/Grease/Macaw/Dwarf.hs [hunk 9]
```diff
@@ -264,45 +281,59 @@ shapeFromDwarf aContext tyUnrollBound sub =
...
    in
-    Shape.ParsedShapes{Shape._getParsedShapes = Map.fromList ascParams}
+    do
+      Maybe.maybe
+        (pure ())
+        ( \((_, vr), errMsg) ->
+            let msg = "Stopped parsing at variable: \n" ++ show vr ++ "\nVariable error message:\n" ++ errMsg
+             in doLog gla $ DwarfDiagnostic.FailedToParse sub msg
+        )
+        err
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf.hs]:
```suggestion
      for_ @Maybe err $ \((_, vr), errMsg) ->
        let msg = "Stopped parsing at variable: \n" ++ show vr ++ "\nVariable error message:\n" ++ errMsg
         in doLog gla $ DwarfDiagnostic.FailedToParse sub msg
```

File: grease/src/Grease/Macaw/Dwarf/Diagnostic.hs (hunk 7 above)
Comment (langston-barrett) [reply grease/src/Grease/Macaw/Dwarf/Diagnostic.hs:10]: Also the error messages do a lot of string-appending, which is not O(n).

File: grease/src/Grease/Macaw/Dwarf.hs [hunk 10]
```diff
@@ -264,45 +281,59 @@ shapeFromDwarf aContext tyUnrollBound sub =
...
+              ( \x ->
+                  let rs = cuRanges x
+                      isInCU range =
+                        let begin = rangeBegin range
+                            end = rangeEnd range
+                         in begin <= addr
+                              && addr
+                                < end
+                   in any isInCU rs
+              )
```
Comment (langston-barrett) [inline grease/src/Grease/Macaw/Dwarf.hs]: Feels like this could be `let`-bound and given a meaningful name

File: grease/src/Grease/Macaw/Dwarf/Diagnostic.hs (hunk 7 above)
Comment (2over12) [reply grease/src/Grease/Macaw/Dwarf/Diagnostic.hs:10]: the majority of this message is from the Dwarf error itself which is simply a string so im not sure there is a ton to be done
