### PR TITLE
Fix parsing of exact-byte RLE

### LINKED ISSUE #238: `--initial-precondition` parse error involving RLE for bytes
`grease` successfully parses this initial precondition file, which specifies that the first argument should point to a 32-bit `0` value:

```
rdi: 00+0000000000000000

00: 00*4
```

Now let us suppose we want the first argument to point to the value `1` instead. I tried this:

```
rdi: 00+0000000000000000

00: 01 00*3
```

But surprisingly, `grease` fails to parse this:

```
$ cabal -v0 run exe:grease -- grease-cli/tests/x86/id.x64.cbl --symbol test --initial-precondition initial-precondition2.txt
Analyzing from entrypoint 'test'
grease: initial-precondition2.txt:3:10:
  |
3 | 00: 01 00*3
  |          ^
unexpected '*'
expecting end of input, newline, or space
```

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #238.

### CODE REVIEW

File: grease/src/Grease/Shape/Parse.hs [hunk 1]
```diff
@@ -315,20 +316,17 @@ hexCharsToWord8 c1 c2 = Tuple.fst (List.head (Numeric.readHex (c1:c2:[])))
...
+parseExactly :: Parser (Seq Word8)
+parseExactly = mconcat <$> trySepBy1 parseExactlyByte memShapeSep
+
+-- | Parse either a byte (e.g., @e0@) or a RLE'd byte (e.g., @e0*0a@).
+parseExactlyByte :: Parser (Seq Word8)
+parseExactlyByte = do
+  (c0, c1) <- (,) Functor.<$> MPC.hexDigitChar Applicative.<*> MPC.hexDigitChar
+  num <-
+    (MPC.char '*' Applicative.*> MPCL.hexadecimal) MP.<|>
+      (MP.notFollowedBy MPC.hexDigitChar Applicative.*> Applicative.pure 1)
```
Comment (RyanGlScott) [inline grease/src/Grease/Shape/Parse.hs]: For readability's sake, could you put each of these parsers into their own definition? Something like:

```hs
  let rle = MPC.char '*' Applicative.*> MPCL.hexadecimal
  let nonRle = MP.notFollowedBy MPC.hexDigitChar Applicative.*> Applicative.pure 1
  num <- rle MP.<|> nonRle
```

File: grease/src/Grease/Shape/Parse.hs [hunk 2]
```diff
@@ -315,20 +316,17 @@ hexCharsToWord8 c1 c2 = Tuple.fst (List.head (Numeric.readHex (c1:c2:[])))
...
-    trySepBy1 (MP.lookAhead justTwoHex Applicative.*> twoHex) memShapeSep
-  where twoHex = (,) Functor.<$> MPC.hexDigitChar Applicative.<*> MPC.hexDigitChar
-        justTwoHex = twoHex Applicative.<* MP.notFollowedBy MPC.hexDigitChar
+parseExactly :: Parser (Seq Word8)
+parseExactly = mconcat <$> trySepBy1 parseExactlyByte memShapeSep
+
+-- | Parse either a byte (e.g., @e0@) or a RLE'd byte (e.g., @e0*0a@).
+parseExactlyByte :: Parser (Seq Word8)
+parseExactlyByte = do
+  (c0, c1) <- (,) Functor.<$> MPC.hexDigitChar Applicative.<*> MPC.hexDigitChar
```
Comment (RyanGlScott) [inline grease/src/Grease/Shape/Parse.hs]: How about just:

```suggestion
  c0 <- MPC.hexDigitChar
  c1 <- MPC.hexDigitChar
```

This avoids an intermediate tuple.

File: grease/src/Grease/Shape/Parse.hs [hunk 3]
```diff
@@ -315,20 +316,17 @@ hexCharsToWord8 c1 c2 = Tuple.fst (List.head (Numeric.readHex (c1:c2:[])))
...
-parseExactlyExplicit =
-  Functor.fmap (Tuple.uncurry hexCharsToWord8) Functor.<$>
-    trySepBy1 (MP.lookAhead justTwoHex Applicative.*> twoHex) memShapeSep
-  where twoHex = (,) Functor.<$> MPC.hexDigitChar Applicative.<*> MPC.hexDigitChar
-        justTwoHex = twoHex Applicative.<* MP.notFollowedBy MPC.hexDigitChar
+parseExactly :: Parser (Seq Word8)
+parseExactly = mconcat <$> trySepBy1 parseExactlyByte memShapeSep
+
+-- | Parse either a byte (e.g., @e0@) or a RLE'd byte (e.g., @e0*0a@).
+parseExactlyByte :: Parser (Seq Word8)
```
Comment (RyanGlScott) [inline grease/src/Grease/Shape/Parse.hs:318]: It might be worth a comment here explaining why we don't use `parseRle` in the implementation of this function.

Comment (RyanGlScott) [inline grease/src/Grease/Shape/Parse.hs:318]: Relatedly, after this PR, the only two call sites to `parseRle` are in `parseUninitRle` and `parseInitRle`, both of which simply take the third element of the tuple and discard the rest. I think we could simplify the type of `parseRle` to just:

```hs
parseRle :: Parser Char -> Parser Bytes
```

File: grease/src/Grease/Shape/Parse.hs (hunk 2 above)
Comment (langston-barrett) [reply grease/src/Grease/Shape/Parse.hs]: Good call
