### PR TITLE
Documentation and improved error messages for S-expression programs

### LINKED ISSUE #19: UX tests
@langston-barrett says:

-----

It would be helpful to have UX tests that compare GREASE's log output to a file. This probably wouldn't be too big of a lift, because much of GREASE is already parameterized by a "log action" that could be used to capture said output.

### LINKED ISSUE #164: Improve error messages for S-expression programs
The exceptions related to type-checking S-expression programs mention Macaw, which presumably most users won't know/care about. They should instead link to some user-facing docs about the register struct.

While we're in the area, we should factor out a function for type-checking these CFGs into a `where`-clause for readability, along the following lines:
```haskell
    checkCfgSignature ::
      forall s init ret.
      CCR.CFG (MS.MacawExt arch) s init ret ->
      IO (CCR.SomeCFG
           (MS.MacawExt arch)
           (Ctx.EmptyCtx Ctx.::> MS.ArchRegStruct arch)
           (MS.ArchRegStruct arch))
    checkCfgSignature regCfg = do
      let expectedArgTys = Ctx.singleton (GM.regStructRepr archCtx)
      let expectedRet = GM.regStructRepr archCtx
      let argTys = CCR.cfgArgTypes regCfg
      let ret = CCR.cfgReturnType regCfg
      Refl <-
        case testEquality argTys expectedArgTys of
          Just r ->
            pure r
          Nothing ->
            throw $ GreaseException -- ...
      Refl <-
        case testEquality ret expectedRet of
          Just r ->
            pure r
          Nothing ->
            throw $ GreaseException -- ...
      pure $ CCR.SomeCFG regCfg
```

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #164. Also fixes #19 by adding a single UX test.

### CODE REVIEW

File: grease-cli/src/Grease/Main.hs [hunk 1]
```diff
@@ -799,6 +786,44 @@ simulateMacawCfgs la halloc macawCfgConfig archCtx simOpts setupHook cfgs = do
           pure (entry, result)
 
     pure (Results (Map.fromList results))
+  where
+    checkCfgSignature ::
```
Comment (RyanGlScott) [inline grease-cli/src/Grease/Main.hs:792]: Worth including a comment saying what this function does at a glance.

File: grease-cli/tests/Main.hs [hunk 2]
```diff
@@ -258,6 +258,7 @@ main = do
         , "prop"
         , "refine"
         , "sanity"
+        , "ux"
```
Comment (RyanGlScott) [inline grease-cli/tests/Main.hs:261]: Make sure to mention this subdirectory in `doc/tests.md`.

**Review by RyanGlScott — APPROVED** [review]
