### PR TITLE
macaw: Catch an exception from Stubs, turn it into a proper error

### LINKED ISSUE #478: Uncaught exception: `CrucibleSyntaxFunctionNotFound`
```
cabal run exe:grease -- --symbol REDACTED REDACTED.so --initial-precondition shapes.txt --loop-bound 800 --overrides strlen.x64.cbl

Exception: You have encountered a bug in GREASE's implementation.
*** Please create an issue at https://github.com/GaloisInc/grease/issues

%< ---------------------------------------------------
  Revision:  9020f6362053ed4177b72c334a54973167f286e7
  Branch:    main (uncommited files present)
  Location:  main
  Message:   Uncaught exception
             CrucibleSyntaxFunctionNotFound strlen "strlen.x64.cbl"
CallStack (from HasCallStack):
  panic, called at src/Grease/Panic.hs:24:9 in grease-0.1.0.0-inplace:Grease.Panic
  panic, called at src/Grease/Main.hs:2300:46 in grease-exe-0.1.0.0-inplace:Grease.Main
%< ---------------------------------------------------
```
```
(defun @test ((ptr (Ptr 64))) (Bitvector 64)
  (start start:
    (let off (pointer-to-bits ptr))
    (println "--------------")
    (println (show off))
    (return off)))
```
This is because the override is named `@test`. The exception comes from stubs:

https://github.com/GaloisInc/stubs/blob/bd481bde583490f2e7faababbca2ac9f9f9a0054/stubs-wrapper/src/Stubs/Wrapper/Exception.hs#L14

We should print out a nicer error message.

### PR DESCRIPTION
**Pull request by langston-barrett**
Fixes #478. Made with Claude Code.

### CODE REVIEW

File: grease/src/Grease/Macaw/Overrides/SExp.hs [hunk 1]
```diff
@@ -7,9 +8,11 @@
 -- Maintainer       : GREASE Maintainers <grease@galois.com>
 module Grease.Macaw.Overrides.SExp (
   MacawSExpOverride (..),
+  MacawSExpOverrideError (..),
   loadOverrides,
 ) where
 
+import Control.Exception qualified as X
```
Comment (2over12) [inline grease/src/Grease/Macaw/Overrides/SExp.hs:13]: Is X the preferred name for this module? i think i recall seeing it used elsewhere but im not sure

Comment (langston-barrett) [reply grease/src/Grease/Macaw/Overrides/SExp.hs:13]:
```
rg 'import Control.Exception qualified'

grease/src/Grease/Internal.hs:import Control.Exception qualified as X
grease-exe/tests/Main.hs:import Control.Exception qualified as X
grease/src/Grease/Macaw/Overrides/SExp.hs:import Control.Exception qualified as X
deps/crucible/crucible-debug/src/Lang/Crucible/Debug/Commands.hs:import Control.Exception qualified as X
deps/macaw/macaw-dump/src/Data/Macaw/Dump/Discover.hs:import Control.Exception qualified as X
deps/crucible/crucible-debug/src/Lang/Crucible/Debug/Complete.hs:import Control.Exception qualified as X
deps/crucible/crucible/src/Lang/Crucible/Simulator/RecordAndReplay.hs:import Control.Exception qualified as X
```
