### PR TITLE
Remove imports from prelude, fix up conflicts/unused imports

### LINKED ISSUE #144: Remove some explicit `Prelude` imports
These are relics of a time when GREASE used `-XNoImplicitPrelude` by default. They are unnecessary, inconsistent, and verbose, and they should be removed.

https://github.com/search?q=repo%3AGaloisInc%2Fgrease%20%2Fimport%20Prelude%20%5C(%2F&type=code

### PR DESCRIPTION
**Pull request by 2over12**
Fixes #144

### CODE REVIEW

File: grease/src/Grease/AssertProperty.hs [hunk 1]
```diff
@@ -31,7 +28,7 @@ import Lang.Crucible.CFG.Expr qualified as C
 import Lang.Crucible.CFG.Reg qualified as C.Reg
 import Lang.Crucible.LLVM.MemModel qualified as Mem
 import Lang.Crucible.Utils.RegRewrite qualified as C
-import Prelude (Bool(False), toInteger)
+
```
Comment (langston-barrett) [inline grease/src/Grease/AssertProperty.hs]: Let's remove this extra whitespace (same comment applies elsewhere)

File: grease/src/Grease/BranchTracer.hs [hunk 2]
```diff
@@ -42,8 +42,8 @@ branchTracerFeature ::
   C.ExecutionFeature p sym ext rtp
 branchTracerFeature tracer = C.ExecutionFeature $
   \case
-    C.SymbolicBranchState pred tpath fpath mergePoint simState -> do
-      getBranchTracer tracer pred tpath fpath mergePoint simState
+    C.SymbolicBranchState st_pred tpath fpath mergePoint simState -> do
+      getBranchTracer tracer st_pred tpath fpath mergePoint simState
```
Comment (langston-barrett) [inline grease/src/Grease/BranchTracer.hs]: Our normal convention is to use `camelCase` for local variables, so let's call this `stPred`
```suggestion
    C.SymbolicBranchState stPred tpath fpath mergePoint simState -> do
      getBranchTracer tracer stPred tpath fpath mergePoint simState
```

File: grease/src/Grease/LLVM/Overrides.hs [hunk 3]
```diff
@@ -426,8 +415,8 @@ registerLLVMModuleOverrides ::
   -- ^ Return a map of public function names to their overrides. This map does
   -- not include names of auxiliary functions, as they are intentionally hidden
   -- from other overrides.
-registerLLVMModuleOverrides la builtinOvs paths bak halloc llvmCtx fs mod = do
-  let decls = L.modDeclares mod
+registerLLVMModuleOverrides la builtinOvs paths bak halloc llvmCtx fs llmod = do
+  let decls = L.modDeclares llmod
```
Comment (langston-barrett) [inline grease/src/Grease/LLVM/Overrides.hs]: Same comment re: naming
```suggestion
registerLLVMModuleOverrides la builtinOvs paths bak halloc llvmCtx fs llMod = do
  let decls = L.modDeclares llMod
```

File: grease/src/Grease/Shape/Pointer.hs [hunk 4]
```diff
@@ -281,8 +272,8 @@ ptrTarget = PtrTarget . Foldable.foldl' go Seq.empty
     go s (Uninitialized 0) = s
     go s (Initialized _tag 0) = s
     go Seq.Empty memShape = Seq.singleton memShape
-    go accum@(pfx Seq.:|> last) memShape =
-      case merge last memShape of
+    go accum@(pfx Seq.:|> last_seq) memShape =
+      case merge last_seq memShape of
```
Comment (langston-barrett) [inline grease/src/Grease/Shape/Pointer.hs]:
```suggestion
    go accum@(pfx Seq.:|> lastElem) memShape =
      case merge lastElem memShape of
```

File: grease/src/Grease/Shape/Pointer.hs [hunk 5]
```diff
@@ -363,8 +354,8 @@ ptrTargetToPtrs ::
 ptrTargetToPtrs proxy tag tgt =
   let sz = ptrTargetSize proxy tgt
       ptrBytes = Bytes.bitsToBytes (C.widthVal ?ptrWidth)
-      (nPtrs, rem) = sz `divMod` ptrBytes
-      nPtrs' = Bytes.bytesToInteger $ if rem == 0 then nPtrs else nPtrs + 1
+      (nPtrs, rem_bts) = sz `divMod` ptrBytes
+      nPtrs' = Bytes.bytesToInteger $ if rem_bts == 0 then nPtrs else nPtrs + 1
```
Comment (langston-barrett) [inline grease/src/Grease/Shape/Pointer.hs]:
```suggestion
      (nPtrs, remBits) = sz `divMod` ptrBytes
      nPtrs' = Bytes.bytesToInteger $ if remBits == 0 then nPtrs else nPtrs + 1
```

File: grease/src/Grease/Shape/Print.hs [hunk 6]
```diff
@@ -17,11 +17,8 @@ module Grease.Shape.Print
   , printNamedShapesFiltered
   , printNamedShapes
   , printNamed
-  , print
```
Comment (langston-barrett) [inline grease/src/Grease/Shape/Print.hs:20]: We probably want to keep exporting this, perhaps try
```haskell
import Prelude hiding (print)
```
to clear up the ambiguity

File: grease/src/Grease/Shape/Print.hs [hunk 7]
```diff
@@ -182,7 +169,7 @@ printNamed ::
   Shape ext tag ty ->
   Printer w (PP.Doc ann)
 printNamed name s =
-  ((PP.pretty name PP.<> ": ") PP.<>) Functor.<$> print s
+  ((PP.pretty name PP.<> ": ") PP.<>) Functor.<$> Grease.Shape.Print.print s
```
Comment (langston-barrett) [inline grease/src/Grease/Shape/Print.hs]: See above comment re: importing `Prelude` to resolve this ambiguity

**Review by langston-barrett — COMMENTED** [review]
Awesome, this looks like a great cleanup! I realize that this is a draft, but I figured I'd just leave a few comments for you to consider while you work.

**Review by langston-barrett — APPROVED** [review]
