### PR TITLE
DWARF defaults test case

### LINKED ISSUE #504: Test case for "default shape for failed pointers and field members"
#502 landed without a test case, but it could use one.

### PR DESCRIPTION
**Pull request by 2over12**
Fixes #504

### CODE REVIEW

File: grease-exe/tests/sanity/pass/dwarf-default-for-field-members-and-pointers/test.c [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  char z;
+} y;
+
+struct bar {
+  int (*somefn)(int);
+  int x;
+  y *blah;
+};
+
+int foo(int x, int *y, struct bar *z) { return x + *y + z->x; }
```
Comment (langston-barrett) [inline grease-exe/tests/sanity/pass/dwarf-default-for-field-members-and-pointers/test.c]: Why not just

```suggestion
int test(int x, int *y, struct bar *z) { return z->x; }
```

File: grease-exe/tests/sanity/pass/dwarf-default-for-field-members-and-pointers/test.c [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+// all: flags {"--symbol", "foo", "--use-debug-info-types", "--no-heuristics"}
```
Comment (langston-barrett) [inline grease-exe/tests/sanity/pass/dwarf-default-for-field-members-and-pointers/test.c]: In most of our tests, the main function is named `test`:

```suggestion
// all: flags {"--symbol", "test", "--use-debug-info-types", "--no-heuristics"}
```

**Review by langston-barrett — APPROVED** [review]
